#!/usr/bin/env python3
# encoding: utf-8
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Command line tool to transform a stereophonic sound (2 channels) WAVE file. Version 2.0.0.20190308

# Copyright (c) 2017 eel3
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

"""Command line tool to transform a stereophonic sound (2 channels)
   WAVE file.
"""

import argparse
import functools
import struct
import sys
import wave


def eprint(*args, **keywords):
    """Wrapper function of print() (for error messages).

    Args:
        *args (tuple): Variable length argument list.
        **keywords (dict[str, Any]): Arbitrary keyword arguments.
    """
    print(sys.argv[0] + ':', *args, file=sys.stderr, **keywords)


def make_frame_left(samples, _, __):
    """Pick up only left-side PCM sample and make PCM frame.

    Args:
        samples (list[bytes]): PCM samples (left, right).
        _ (int): Unused parameter.
        __ (str): Unused parameter.

    Returns:
        bytes: PCM frame (left, left).
    """
    return samples[0] * 2


def make_frame_mix(samples, sampwidth, fmt):
    """Mix left/right PCM sample and make PCM frame.

    Args:
        samples (list[bytes]): PCM samples (left, right).
        sampwidth (int): 1 sample size in byte.
        fmt (str): pack/unpack format string.

    Returns:
        bytes: PCM frame (mixed, mixed).
    """
    def unpack_sample(sample):
        """Unpack PCM sample to integer.

        Args:
            sample (bytes): PCM sample.

        Returns:
            int: Unpacked PCM sample.
        """
        bytes = struct.unpack_from(fmt, sample[::-1])
        return functools.reduce(lambda x, y: (x << 8) + y, bytes)

    def pack_pcm(pcm):
        """Pack integer to PCM sample.

        Args:
            pcm (int): Unpacked PCM sample.

        Returns:
            bytes: PCM sample.
        """
        bytes = []
        for i in range(sampwidth):
            bytes.append(pcm & 0xFF)
            pcm >>= 8
        return struct.pack(fmt, *bytes)

    left_pcm = unpack_sample(samples[0])
    right_pcm = unpack_sample(samples[1])
    mixed_pcm = (left_pcm + right_pcm) // 2
    sample = pack_pcm(mixed_pcm)

    return sample * 2


def make_frame_right(samples, _, __):
    """Pick up only right-side PCM sample and make PCM frame.

    Args:
        samples (list[bytes]): PCM samples (left, right).
        _ (int): Unused parameter.
        __ (str): Unused parameter.

    Returns:
        bytes: PCM frame (right, right).
    """
    return samples[1] * 2


def make_frame_swap(samples, _, __):
    """Swap left/right PCM sample and make PCM frame.

    Args:
        samples (list[bytes]): PCM samples (left, right).
        _ (int): Unused parameter.
        __ (str): Unused parameter.

    Returns:
        bytes: PCM frame (right, left).
    """
    return samples[1] + samples[0]


make_frame_table = {
    'left':  make_frame_left,
    'mix':   make_frame_mix,
    'right': make_frame_right,
    'swap':  make_frame_swap,
}
"""Selection list of PCM frame transform function.
"""


def tswav(wavfile, outfile, transform):
    """Read RIFF WAVE file, transform PCM data, write to another file.

    Args:
        wavfile (str): Input file name.
        outfile (str): Output file name.
        transform (str): Transform type.
    """
    wr = wave.open(wavfile, 'rb')

    nchannels = wr.getnchannels()
    if nchannels != 2:
        wr.close()
        raise ValueError('require 2 channels WAVE file')
    sampwidth = wr.getsampwidth()
    framewidth = sampwidth * nchannels
    nframes = wr.getnframes()

    try:
        ww = wave.open(outfile, 'wb')
    except:
        wr.close()
        raise

    ww.setnchannels(nchannels)
    ww.setsampwidth(sampwidth)
    ww.setframerate(wr.getframerate())
    ww.setnframes(nframes)
    ww.setcomptype(wr.getcomptype(), wr.getcompname())

    make_frame = make_frame_table[transform]
    fmt = '%dB' % sampwidth

    frames = wr.readframes(nframes)
    it = (frames[i:i+framewidth] for i in range(0, len(frames), framewidth))
    for frame in it:
        samples = [frame[i:i+sampwidth] for i in range(0, framewidth, sampwidth)]
        ww.writeframesraw(make_frame(samples, sampwidth, fmt))

    ww.close()
    wr.close()


def parse_args():
    """Parse CLI arguments.

    Returns:
        tuple[argparse.Namespace, list[str]]: Results of argument parsing.
    """
    parser = argparse.ArgumentParser(description=
            'Command line tool to transform a stereophonic sound (2 channels) WAVE file.')

    parser.add_argument('files', metavar='file', nargs='+',
                        help='RIFF WAVE file')
    parser.add_argument('-o', '--output-files', metavar='file', nargs='+',
                        required=True, help='place output in file')
    parser.add_argument('-t', '--transform', nargs=1, default=['mix'],
                        choices=sorted(make_frame_table.keys()),
                        help='transform type')
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s 2.0.0')

    return parser.parse_known_args()


def main():
    """Main routine function.
    """
    args = parse_args()
    retval = 0

    infiles = args[0].files
    outfiles = args[0].output_files

    if len(infiles) != len(outfiles):
        eprint('error: The number of output files must be equal to the number of intput files')
        sys.exit(1)

    for (infile, outfile) in zip(infiles, outfiles):
        try:
            tswav(infile, outfile, args[0].transform[0])
        except Exception as e:
            eprint(e)
            retval = 1

    sys.exit(retval)


if __name__ == '__main__':
    main()
